### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mixcomic** [takattowo/takattoFS2#10]
There is no function to display the actual attribute.

**Comment by takattowo** [comment]
If you mentioned an old patch that showed the un-nerfed attribute you have. Then it is still working (technically, there maybe some miscalculations), you can find it in the mod folder and manually import it, however you will not be able to modify your attributes until you uninstall that mod.

Do we have an update for it? I don't know; I have cancelled this project as I needed to focus on real-life stuff. Maybe in the future, when I feel like it.

And, **Happy New Year!**

**Comment by mixcomic** [comment]
Mod Where?
