### ISSUE TITLE
unban me rq

### ISSUE THREAD

**Issue by slightlyepic** [takattowo/takattoFS2#7]
pls thx

**Comment by takattowo** [comment]
who?

**Comment by slightlyepic** [comment]
Zeeman

**Comment by takattowo** [comment]
ok

**Comment by slightlyepic** [comment]
wow thanks

**Comment by slightlyepic** [comment]
you forgot to update the release now it wont launch coz the version number is different .__.

**Comment by takattowo** [comment]
im lazy to draft new version so i just update the zip from 2928

**Comment by slightlyepic** [comment]
im still banned, maybe coz something is locally set somewhere on my pc, did the repair thing but its still the same

**Comment by slightlyepic** [comment]
ok its coz u removed the wrong id from the blocked users list 
![image](https://user-images.githubusercontent.com/42976178/194078291-4e263cbf-5229-4e85-8740-6896cc4f6c86.png)
lmao

**Comment by slightlyepic** [comment]
![809867393371209748](https://user-images.githubusercontent.com/42976178/194271352-dfcd0d6a-c186-4b04-b2a2-3e69f136cc0e.gif)

**Comment by takattowo** [comment]
if you are smart, you'd know why.
i have removed you from the ban list, but other remains. unfortunately, i have no way to lift it without keeping the others.

i suggest reinstalling windows.

**Comment by slightlyepic** [comment]
im not kidding ive tested this thrice already but my id is `SkFIW0hKXUxbE01ITU9cRQ==` and not the one youve removed, so even if i am successful in finding whatever secret registry keys youve set it still wont matter because my id is still there

**Comment by takattowo** [comment]
sadly, that id is for another, just double check, happy yet?
consider doing what i said, do a clean install, if necessary, i am sorry but it is the best i could do.

**Comment by slightlyepic** [comment]
ok ill do a clean install, thanks btw

**Comment by takattowo** [comment]
i will assume you have it fixed, i will be closing this ticket tomorrow if you have no comment.

**Comment by slightlyepic** [comment]
maybe also unban from the discord?
