### ISSUE TITLE
unban me rq

### ISSUE THREAD

**Issue by hndful** [takattowo/takattoFS2#8]
tard XD

**Comment by takattowo** [comment]
who?

**Comment by hndful** [comment]
me

**Comment by hndful** [comment]
> who?

Please, I'm sorry

**Comment by takattowo** [comment]
about? i need a reasson.

**Comment by hndful** [comment]
> about? i need a reasson.

Even if you don't know who I am, I am sorry for being an arrogant prick to you and everyone else; I'm sorry for trashtalking and all the remarks I've made about you.

**Comment by takattowo** [comment]
okay.
